# Generated by Django 3.1.7 on 2021-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceApp', '0002_product_price_by_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_by_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
